[env:esp32s3]
platform = espressif32
board = esp32s3devkitc1
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient
    bblanchon/ArduinoJson
lib_extra_dirs =
    ../../lib
build_flags =
    -DDEVICE_ID=\"0101\"
